module AdultTimeDL
  class FatalError < StandardError
  end

  class APIError < StandardError
    attr_reader endpoint: untyped

    attr_reader code: untyped

    attr_reader body: untyped

    def initialize: (endpoint: untyped, code: untyped, body: untyped) -> void

    def fetch_error_message: () -> untyped

    def message: () -> ::String
  end

  class NotFoundError < APIError
  end

  class BadRequestError < APIError
  end

  class BadGatewayError < APIError
  end

  class UnhandledError < APIError
  end

  class UnauthorizedError < APIError
  end

  def self.logger: (**untyped opts) -> untyped
end
