AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: [ 'describe', 'context' ]
  Exclude:
    - spec/**/*
    - xxx_download.gemspec

Style/OptionalBooleanParameter:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false