AllCops:
  TargetRubyVersion: 2.6.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context' ]
  Exclude:
    - spec/**/*
    - adulttime_dl.gemspec

Style/OptionalBooleanParameter:
  Enabled: false