module XXXDownload
  module Net
    class AlgoliaCredentials < Base
      include HTTParty

      # ADULT_TIME_URL = "https://www.adulttime.com"
      API_KEY_REGEX: ::Regexp

      attr_reader algolia_params: untyped

      def initialize: () -> void

      private

      def set_algolia_params: (?refresh: bool) -> untyped

      def extract_algolia_credentials!: () -> untyped

      def algolia_params_hash: (untyped match) -> untyped

      def parse_homepage_script: () -> untyped

      def adulttime_homepage: () -> untyped
    end
  end
end
