module XXXDownload
  module Net
    class Query < AlgoliaCredentials
      attr_reader actor_name: untyped

      INDEX_ENDPOINT: String

      INDEX_NAME: String

      def scenes: (String actor_name) -> untyped

      def request: () -> { requests: ::Array[{ indexName: untyped, params: untyped }] }

      def params: (untyped actor_name) -> untyped

      def actors_facet_filters: (untyped actor_name) -> ::Array[::String]

      def default_facet_filters: () -> untyped

      def content_tags_facet_filters: () -> ::Array["content_tags:straight" | "content_tags:lesbian"]

      def released_scenes_facet_filter: () -> "upcoming:0"
    end
  end
end
